### PR TITLE
Add electron-forge to take care of building & packaging

### PR DESCRIPTION
**Pull request by 0x6431346e**
I've added electron-forge for building because it does some compiling/caching which seems to speeds things up a bit (not for development though): 

after_yarn_package_or_make
(bottom is the packaged app, top is development)

I think it's important to note that when having a simple react page (import `react` + `react-dom` and print hello world) the loading time is blazing fast ( <500ms), which means that IPFS/Photonkit most likely contribute to the slowness as well:

blank_react_window
(top is the packaged app, bottom is development)

### CODE REVIEW

**Comment by koalalorenzo** [comment]
You don't know how much happy I am by noticing a jump from 3s to 600ms for an Hello World! Definitively better!

**Comment by 0x6431346e** [comment]
I guess I will look into why Photonkit is slow as part of https://dev.siderus.team/issues/42

**Comment by koalalorenzo** [comment]
BTW, going to review. Could you check the failing tests?

**Comment by 0x6431346e** [comment]
Yep

**Pull request merged**
